version: '3.4'

services:
  web:
      # Сборка образа для сервиса django из текущей директории
       build: .
      # Задание имени контейнера для сервиса django
       container_name: django
       # Задание команды, которую нужно запустить при запуске контейнера для сервиса web
       command: python manage.py runserver 0.0.0.0:8000
       volumes:
          - .:/usr/src/app
       # Открытие порта на хостовой машине и перенаправление на порт в контейнере
       ports:
          - 8000:8000
      # Зависимость от другого сервиса по очередности запуска
       depends_on:
         - pgdb
  pgdb:
    # Использование готового образа postgres
    image: postgres:15
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=netology_stocks_products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=as798360
      # Задание имени контейнера для сервиса pgdb
    container_name: pgdb
    # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
volumes:
  pgdbdata: null


